name: shop_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  http: ^0.13.0
  rounded_loading_button: ^2.1.0
  dio: ^4.0.6
  lottie: ^2.1.0
  bottom_sheet_bar: ^2.3.8
  intl: ^0.18.0
  badges: ^2.0.3
  flutter_slidable: ^2.0.0
  pull_to_refresh: ^2.0.0
  custom_radio_grouped_button: ^2.1.2+2
  dialog_alert: ^0.0.3
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - lib/assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
  uses-material-design: true

